# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
          my_mongo_provider:
                      mongodb: {class: QuestBundle\Document\User, property: login}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
                login_path: login
                check_path: login
                provider: my_mongo_provider
                use_forward: false
                always_use_default_target_path: false
                default_target_path: /vilmins/articles/
                target_path_parameter:          _target_path
                use_referer:                    false

            logout:
                 path:   /logout
                 target: /

    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/vilmins*, roles: ROLE_ADMIN }

    encoders:
            QuestBundle\Document\User:
                  id: md5password.encoder
